### ISSUE TITLE
Ability to enable segment.com telemetry

### ISSUE THREAD

**Issue by brewsoftware** [MYOB-Technology/starbird-issues#20]
When I include the following as per the docs in our local.json config.  

```
> 
> "segment": {
>     "key" : "xxx"
>   }
> 
```

Our test pipeline stops working with errors relating to segment. 
```

 TypeError: Cannot read property 'parentNode' of undefined
      
      at Array.analytics.load (node_modules/@starbird/sdk/lib/segment/loadSegment.js:30:8)
      at Object.<anonymous>.exports.default (node_modules/@starbird/sdk/lib/segment/loadSegment.js:37:15)
      at Object.<anonymous>.exports.default (node_modules/@starbird/sdk/lib/segment/index.js:30:29)
      at Object.<anonymous>.exports.default (node_modules/@starbird/sdk/lib/index.js:72:36)
      at Object.<anonymous> (src/jest.setup.js:12:60)

```

**Comment by igormyob** [comment]
closing for inactivity
